// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum DatePartSelector
{
	year("89490c4c-aec2-4c46-b4a3-786b47c4a9de"),
	month("75e67543-53f6-4565-8b44-ae5ac4f09865"),
	day("6514e784-3c42-4e56-9018-e6898c1ba86a");

	private final java.lang.String i18nCaptionKey;
	
	private DatePartSelector(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
