// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum DatePartSelector
{
	year("47b590a2-e008-4b52-9b28-b117be119e01"),
	month("ecede86c-1399-423d-8683-6d8b5938c1db"),
	day("c76047a9-7ff3-4b23-b55a-59bd6e2103cc");

	private final java.lang.String i18nCaptionKey;
	
	private DatePartSelector(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
