// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace("c7c6940b-a830-4256-8711-5b6a2383895a"),
	Debug("082f3c7b-3bc3-4633-961b-b31bd440d65f"),
	Info("9e06ac0e-e7ac-407c-a8a4-a03a9b5c5062"),
	Warning("461170a6-f49e-4b82-ad36-4a1580c96b9a"),
	Error("e7bf2011-3720-4e18-9b25-069817cae1b4"),
	Critical("eb790670-9b2d-4d49-ba9e-cb1bc41fc2a0");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
