// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS("67fd74c7-5364-4109-afeb-1d37251a8792"),
	FORMATTING("787e9a50-0695-4357-9742-0c97cef4aa0d"),
	IMAGES("82c56bb0-1c90-4123-ac4a-f77035011eea"),
	LINKS("3e40eee5-5a3e-4e69-9164-5aa06eb1aa0d"),
	STYLES("eae55ed9-9cf8-4146-99f8-31309b003858"),
	TABLES("8a608520-3aba-4ed9-84b5-47e16209a597");

	private final java.lang.String i18nCaptionKey;
	
	private SanitizerPolicy(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
