// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("a15903a1-24f2-4f1b-ae43-34067331727d"),
	ISO_8859_1("555c4958-d73e-434b-a182-931d74a1c957"),
	UTF_8("763356ea-df1f-4aeb-bb30-dd5c71b1f1ed"),
	UTF_16BE("fb20e461-01de-4971-b746-c5e782d43db7"),
	UTF_16LE("2be090e8-991d-4847-960a-f81ff5023686"),
	UTF_16("05b827a5-51f9-44fc-9ad0-362e67d41f28");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
