// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("8cfb631e-34e0-4142-b591-ab0e0973f36e"),
	Geocodio("4d2b344c-3b4f-4682-b7a6-d1be6614056d"),
	LocationIQ("06db139c-00d3-4769-92b1-a5a5bfc77a57"),
	MapQuest("bca44417-2c4f-48f4-8b82-aebab1f467df");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
