// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE

import { errorCodes,pick, keepLocalCopy, types } from "@react-native-documents/picker";
import NativeFileDocumentsUtils from "../nativefiledocumentsutils";
import { create } from "mx-api/data";

// END EXTRA CODE

/**
 * @param {string} allowedTypes - Empty to allow any file. One or more key values of enumeration DocumentType. Separate multiple values with a comma
 * @param {boolean} writeToLog
 * @param {string} [notAllowedTypeMessage]
 * @returns {Promise.<MxObject>}
 */
export async function openDocumentPicker(allowedTypes, writeToLog, notAllowedTypeMessage) {
	// BEGIN USER CODE
	const resultMxObj = await create({ entity: "NativeFileDocuments.DocumentPickerResult" });

	try {
		// The contents of the file can only be directly accessed when copying it.
		// Otherwise, Android will return another type of URI that needs to be resolved first 
		const options = {
			mode: "open",
			allowMultiSelection: false
		};

		if (allowedTypes) {
			const allowedTypeArray = [];
			for (const allowedType of allowedTypes.split(",")) {
				const documentPickerType = types[allowedType];
				if (documentPickerType) {
					allowedTypeArray.push(documentPickerType);
				} else {
					const errorMessage = "openDocumentPicker: unknown type: " + allowedType;
					console.error(errorMessage);
					return Promise.reject(new Error(errorMessage)); 
				}
			}
			options.type = allowedTypeArray;
		}

		if (writeToLog) {
			await NativeFileDocumentsUtils.writeToLog({
				actionName: "openDocumentPicker",
				logType: "Parameters",
				logMessage: JSON.stringify(options)
			});
		}

		const [pickResult] = await pick(options);
		if (writeToLog) {
			await NativeFileDocumentsUtils.writeToLog({
				actionName: "openDocumentPicker",
				logType: "Info",
				logMessage: "Picker result: " + JSON.stringify(pickResult)
			});
		}

        const [copyResult] = await keepLocalCopy({
          files: [
            {
              uri: pickResult.uri,
              fileName: pickResult.name ?? 'unknown-file-name',
            },
          ],
          destination: 'cachesDirectory',
        })

		if (writeToLog) {
			await NativeFileDocumentsUtils.writeToLog({
				actionName: "openDocumentPicker",
				logType: "Info",
				logMessage: "Keep local copy result: " + JSON.stringify(copyResult)
			});
		}

        if (copyResult.status === 'success') {
			resultMxObj.set("DocumentPicked", true);
			resultMxObj.set("Name", pickResult.name);
			resultMxObj.set("Uri", copyResult.localUri);
			resultMxObj.set("FileType", pickResult.type);
			resultMxObj.set("HasRequestedType", pickResult.hasRequestedType);
        }

		return resultMxObj;

	} catch(err) {
		if (err.code === errorCodes.OPERATION_CANCELED) {
			if (writeToLog) {
				await NativeFileDocumentsUtils.writeToLog({
					actionName: "openDocumentPicker",
					logType: "Info",
					logMessage: "Cancelled by user"
				});
			}
			return resultMxObj;
		} else {
			if (writeToLog) {
				await NativeFileDocumentsUtils.writeToLog({
					actionName: "openDocumentPicker",
					logType: "Exception",
					logMessage: JSON.stringify(err)
				});
			}
			return Promise.reject(err);
		}
	}

	// END USER CODE
}
