// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("803bc603-841f-42f6-9ad9-acec8fac281d"),
	startsWith("22d5d6c4-4cc3-420f-8650-bf13aad93740"),
	endsWith("6208f070-5f90-4ff0-bcbe-59db45a7d18c"),
	between("ada31f02-fa55-42fc-bcab-e5afe4b4eac5"),
	greater("afabca18-7eb1-4e8e-934d-c38b667b1bff"),
	greaterEqual("3967660f-5b65-48b8-9b9e-45d079883ee7"),
	equal("d178da35-5e1b-4e2a-9e7e-1e766abd4fd0"),
	notEqual("e1e63684-a744-4894-96df-9674fd7f2e6f"),
	smaller("592a9c94-6888-4d20-b216-f1ef45d8ff8e"),
	smallerEqual("790ebce2-8f35-4d74-b69c-d8b0e3281d8b"),
	empty("d9f62a3c-0c3e-4a61-824a-35df90aafe64"),
	notEmpty("c53a7ac5-a6f4-4048-90bf-791a740b285d");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
