// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum DocumentType
{
	audio("cf0a1057-84d4-4d15-8fe8-0da6705e2c15"),
	csv("51d05e0f-9733-4932-80c5-667f1c0913a3"),
	doc("c412aaff-2def-4ad1-8c7a-d16c847334ba"),
	docx("b68b1afb-3c2d-4d3c-8a30-249c7ce9b1e0"),
	json("842c6aad-5779-46d9-a108-ba50c7508f4a"),
	pdf("64cae957-72fa-447b-aaad-4d630f47e6c6"),
	plainText("315eb9eb-5efa-4b33-9974-4f31f4bf8355"),
	ppt("30a2262f-2677-42df-9c07-f47aa13c06c8"),
	pptx("14bd1dc0-c76e-4e80-8ee7-d5d9d8c7812f"),
	video("bca0e82f-1553-4616-97d6-56be35de401d"),
	xls("dbc861a8-4ff0-42ff-94a1-f55fd605d6bc"),
	xlsx("de3f91ab-4708-4ee2-bac2-65868cf1398c"),
	zip("dda4779c-5f0d-414d-96da-44336a2cbafc");

	private final java.lang.String i18nCaptionKey;
	
	private DocumentType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
