// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public class DownloadFileProgress implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject downloadFileProgressMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeFileDocuments.DownloadFileProgress";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LocalUrl("LocalUrl"),
		ContentLength("ContentLength"),
		BytesWritten("BytesWritten"),
		ProgressPercentage("ProgressPercentage"),
		StatusCode("StatusCode"),
		Status("Status"),
		ErrorMessage("ErrorMessage");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DownloadFileProgress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DownloadFileProgress(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject downloadFileProgressMendixObject)
	{
		if (downloadFileProgressMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!downloadFileProgressMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.downloadFileProgressMendixObject = downloadFileProgressMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativefiledocuments.proxies.DownloadFileProgress initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativefiledocuments.proxies.DownloadFileProgress(context, mendixObject);
	}

	public static nativefiledocuments.proxies.DownloadFileProgress load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativefiledocuments.proxies.DownloadFileProgress.initialize(context, mendixObject);
	}

	/**
	 * @return value of LocalUrl
	 */
	public final java.lang.String getLocalUrl()
	{
		return getLocalUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of LocalUrl
	 */
	public final java.lang.String getLocalUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocalUrl.toString());
	}

	/**
	 * Set value of LocalUrl
	 * @param localurl
	 */
	public final void setLocalUrl(java.lang.String localurl)
	{
		setLocalUrl(getContext(), localurl);
	}

	/**
	 * Set value of LocalUrl
	 * @param context
	 * @param localurl
	 */
	public final void setLocalUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String localurl)
	{
		getMendixObject().setValue(context, MemberNames.LocalUrl.toString(), localurl);
	}

	/**
	 * @return value of ContentLength
	 */
	public final java.lang.Long getContentLength()
	{
		return getContentLength(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentLength
	 */
	public final java.lang.Long getContentLength(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ContentLength.toString());
	}

	/**
	 * Set value of ContentLength
	 * @param contentlength
	 */
	public final void setContentLength(java.lang.Long contentlength)
	{
		setContentLength(getContext(), contentlength);
	}

	/**
	 * Set value of ContentLength
	 * @param context
	 * @param contentlength
	 */
	public final void setContentLength(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long contentlength)
	{
		getMendixObject().setValue(context, MemberNames.ContentLength.toString(), contentlength);
	}

	/**
	 * @return value of BytesWritten
	 */
	public final java.lang.Long getBytesWritten()
	{
		return getBytesWritten(getContext());
	}

	/**
	 * @param context
	 * @return value of BytesWritten
	 */
	public final java.lang.Long getBytesWritten(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.BytesWritten.toString());
	}

	/**
	 * Set value of BytesWritten
	 * @param byteswritten
	 */
	public final void setBytesWritten(java.lang.Long byteswritten)
	{
		setBytesWritten(getContext(), byteswritten);
	}

	/**
	 * Set value of BytesWritten
	 * @param context
	 * @param byteswritten
	 */
	public final void setBytesWritten(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long byteswritten)
	{
		getMendixObject().setValue(context, MemberNames.BytesWritten.toString(), byteswritten);
	}

	/**
	 * @return value of ProgressPercentage
	 */
	public final java.math.BigDecimal getProgressPercentage()
	{
		return getProgressPercentage(getContext());
	}

	/**
	 * @param context
	 * @return value of ProgressPercentage
	 */
	public final java.math.BigDecimal getProgressPercentage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ProgressPercentage.toString());
	}

	/**
	 * Set value of ProgressPercentage
	 * @param progresspercentage
	 */
	public final void setProgressPercentage(java.math.BigDecimal progresspercentage)
	{
		setProgressPercentage(getContext(), progresspercentage);
	}

	/**
	 * Set value of ProgressPercentage
	 * @param context
	 * @param progresspercentage
	 */
	public final void setProgressPercentage(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal progresspercentage)
	{
		getMendixObject().setValue(context, MemberNames.ProgressPercentage.toString(), progresspercentage);
	}

	/**
	 * @return value of StatusCode
	 */
	public final java.lang.Integer getStatusCode()
	{
		return getStatusCode(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusCode
	 */
	public final java.lang.Integer getStatusCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StatusCode.toString());
	}

	/**
	 * Set value of StatusCode
	 * @param statuscode
	 */
	public final void setStatusCode(java.lang.Integer statuscode)
	{
		setStatusCode(getContext(), statuscode);
	}

	/**
	 * Set value of StatusCode
	 * @param context
	 * @param statuscode
	 */
	public final void setStatusCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer statuscode)
	{
		getMendixObject().setValue(context, MemberNames.StatusCode.toString(), statuscode);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final nativefiledocuments.proxies.DownloadFileStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final nativefiledocuments.proxies.DownloadFileStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return nativefiledocuments.proxies.DownloadFileStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(nativefiledocuments.proxies.DownloadFileStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, nativefiledocuments.proxies.DownloadFileStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of ErrorMessage
	 */
	public final java.lang.String getErrorMessage()
	{
		return getErrorMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorMessage
	 */
	public final java.lang.String getErrorMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ErrorMessage.toString());
	}

	/**
	 * Set value of ErrorMessage
	 * @param errormessage
	 */
	public final void setErrorMessage(java.lang.String errormessage)
	{
		setErrorMessage(getContext(), errormessage);
	}

	/**
	 * Set value of ErrorMessage
	 * @param context
	 * @param errormessage
	 */
	public final void setErrorMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String errormessage)
	{
		getMendixObject().setValue(context, MemberNames.ErrorMessage.toString(), errormessage);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return downloadFileProgressMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativefiledocuments.proxies.DownloadFileProgress that = (nativefiledocuments.proxies.DownloadFileProgress) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
