// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum DownloadFileStatus
{
	Active("81e9d5f1-afbb-4adb-a502-f401aedab8c2"),
	Complete("2951692d-3310-4e83-a64a-38742b2d87dc"),
	Error("cee3188c-38b5-41ef-a373-c90d2c6a99f6"),
	Cancelled("4e9b84dc-0a62-4599-bd34-abb572ac9c32");

	private final java.lang.String i18nCaptionKey;
	
	private DownloadFileStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
