// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum DownloadFileStatus
{
	Active("3ac8a47f-3827-4057-8934-b3b363a8b150"),
	Complete("ae583119-d758-4377-9215-974b9772d094"),
	Error("cf74bfeb-f041-4469-8c6f-5039cbbc2fde"),
	Cancelled("0b544f88-db06-44a2-a339-0a1492b89d24");

	private final java.lang.String i18nCaptionKey;
	
	private DownloadFileStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
