// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum FileLogLevel
{
	Info("87daa717-1f4a-41cb-99e3-d559e7b5160b"),
	Warning("640bcfc6-1b21-4647-9f3f-1ff5394b9bdf"),
	Error("f2c9426c-aee9-4211-a1e5-f93bd7eab1b0");

	private final java.lang.String i18nCaptionKey;
	
	private FileLogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
