// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum FileLogLevel
{
	Info("b7fa7c55-691b-4671-ba97-7b458e3f608d"),
	Warning("5d30d8b3-9d50-4e2e-b621-93b5eba70387"),
	Error("c75f6329-c5e3-48cf-8359-e2cd77cf9989");

	private final java.lang.String i18nCaptionKey;
	
	private FileLogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
