// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public class HttpHeader implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject httpHeaderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeFileDocuments.HttpHeader";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Key("Key"),
		Value("Value"),
		ResponseHeader("NativeFileDocuments.ResponseHeader"),
		RequestHeader("NativeFileDocuments.RequestHeader");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public HttpHeader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected HttpHeader(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject httpHeaderMendixObject)
	{
		if (httpHeaderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!httpHeaderMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.httpHeaderMendixObject = httpHeaderMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativefiledocuments.proxies.HttpHeader initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativefiledocuments.proxies.HttpHeader(context, mendixObject);
	}

	public static nativefiledocuments.proxies.HttpHeader load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativefiledocuments.proxies.HttpHeader.initialize(context, mendixObject);
	}

	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResponseHeader
	 */
	public final nativefiledocuments.proxies.DownloadFileProgress getResponseHeader() throws com.mendix.core.CoreException
	{
		return getResponseHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseHeader
	 * @throws com.mendix.core.CoreException
	 */
	public final nativefiledocuments.proxies.DownloadFileProgress getResponseHeader(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nativefiledocuments.proxies.DownloadFileProgress result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResponseHeader.toString());
		if (identifier != null) {
			result = nativefiledocuments.proxies.DownloadFileProgress.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResponseHeader
	 * @param responseheader
	 */
	public final void setResponseHeader(nativefiledocuments.proxies.DownloadFileProgress responseheader)
	{
		setResponseHeader(getContext(), responseheader);
	}

	/**
	 * Set value of ResponseHeader
	 * @param context
	 * @param responseheader
	 */
	public final void setResponseHeader(com.mendix.systemwideinterfaces.core.IContext context, nativefiledocuments.proxies.DownloadFileProgress responseheader)
	{
		if (responseheader == null) {
			getMendixObject().setValue(context, MemberNames.ResponseHeader.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResponseHeader.toString(), responseheader.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RequestHeader
	 */
	public final nativefiledocuments.proxies.DownloadFileRequest getRequestHeader() throws com.mendix.core.CoreException
	{
		return getRequestHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestHeader
	 * @throws com.mendix.core.CoreException
	 */
	public final nativefiledocuments.proxies.DownloadFileRequest getRequestHeader(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nativefiledocuments.proxies.DownloadFileRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestHeader.toString());
		if (identifier != null) {
			result = nativefiledocuments.proxies.DownloadFileRequest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RequestHeader
	 * @param requestheader
	 */
	public final void setRequestHeader(nativefiledocuments.proxies.DownloadFileRequest requestheader)
	{
		setRequestHeader(getContext(), requestheader);
	}

	/**
	 * Set value of RequestHeader
	 * @param context
	 * @param requestheader
	 */
	public final void setRequestHeader(com.mendix.systemwideinterfaces.core.IContext context, nativefiledocuments.proxies.DownloadFileRequest requestheader)
	{
		if (requestheader == null) {
			getMendixObject().setValue(context, MemberNames.RequestHeader.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RequestHeader.toString(), requestheader.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return httpHeaderMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativefiledocuments.proxies.HttpHeader that = (nativefiledocuments.proxies.HttpHeader) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
