// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum I18N
{
	ImageCropCancel("7fce25d8-3d66-4b21-9f67-a6f852f51e12"),
	ImageCropConfirm("cc5c89e9-0519-4366-b37c-7efe4f3e6dcf"),
	ImageCropDialogTitle("ea13275d-621e-441b-aed0-3d2449f8490d");

	private final java.lang.String i18nCaptionKey;
	
	private I18N(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
