// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum I18N
{
	ImageCropCancel("c0a7e476-2df4-4426-9c89-e56b405c86b2"),
	ImageCropConfirm("1d5f839c-ec54-4e8e-8cd2-9301e73bd117"),
	ImageCropDialogTitle("25fe42b0-6905-4490-a596-097bb3d33415");

	private final java.lang.String i18nCaptionKey;
	
	private I18N(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
