// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum LogLevel
{
	trace("6ce437d2-feed-4260-a75c-f2d4b3a4fda3"),
	debug("e090bdd0-aa31-4e6a-8957-4364b68a4886"),
	info("1a9de460-6659-4dac-ab95-7450a9ad9fbb"),
	warning("955a6dc4-af59-4aba-a024-d58ae1537283"),
	error("0ee0f596-84e3-40bd-a93b-81056a0cee50"),
	critical("a5709f58-0d1d-47d4-967a-65dbfb1d3bcf"),
	none("3b176fad-1df9-4ccd-b839-9a30f55f932b");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
