// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum LogType
{
	Info("0190564c-4d96-4b33-952a-238fbde7020c"),
	Error("0b190341-3efd-400d-be0d-bf0690133faa"),
	Exception("0cc18d8d-0326-4ff4-9e3d-98552bd1e1f6"),
	Parameters("83fdb8c4-2675-4149-8ef1-f388e1f27c98");

	private final java.lang.String i18nCaptionKey;
	
	private LogType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
