// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum LogType
{
	Info("f70e4597-a653-4cb3-8dbd-03c89e276182"),
	Error("aba57ec6-4c20-4b2e-a46e-ba3e0f91381b"),
	Exception("ab506052-038a-490a-b909-666c77e68e04"),
	Parameters("c3332529-1256-4ca7-a14c-703742a99a9b");

	private final java.lang.String i18nCaptionKey;
	
	private LogType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
