// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum ResizeImageCompressionFormat
{
	JPEG("110f87ec-938a-4fad-8047-97474b0cd4c8"),
	PNG("2c544a6d-8d92-4253-9e54-b5ca91e5b44d"),
	WEBP("0e703204-8ea8-46ea-b463-d5c2418f8ee8");

	private final java.lang.String i18nCaptionKey;
	
	private ResizeImageCompressionFormat(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
