// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum ResizeImageMode
{
	contain("59401f18-01d6-44e8-bc74-7dd2c01d4c79"),
	cover("68ee37f1-046c-4736-a834-71122d40b4e0"),
	stretch("7428ec84-7cdd-402d-9891-59bef84c40c1");

	private final java.lang.String i18nCaptionKey;
	
	private ResizeImageMode(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
