// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum ResizeImageCompressionFormat
{
	JPEG("77fe5b45-35a4-45e5-89fa-e9122d4ac204"),
	PNG("2a44aa7e-833d-4337-be75-5bab5ea3e562"),
	WEBP("25b13faf-8018-4f72-80c5-44861560d253");

	private final java.lang.String i18nCaptionKey;
	
	private ResizeImageCompressionFormat(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
