// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum ResizeImageMode
{
	contain("308b9f09-19df-463e-b518-2a24a507e448"),
	cover("0ad0e658-7c66-4683-8d7d-d1631e8e8773"),
	stretch("8d190afd-7ff5-42c1-9575-1bbc6c88c5c8");

	private final java.lang.String i18nCaptionKey;
	
	private ResizeImageMode(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
