// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum ShareToType
{
	email("ba052dad-a5e5-4996-ae47-9873afbade94"),
	facebook("54f30036-c9a7-4348-bd7e-2b7adc945116"),
	instagram("c36c0393-b636-4966-b52c-8509d3fe7ea4"),
	linkedin("5ffa02df-1825-4e42-8235-16732af8320a"),
	pinterest("3e879603-f708-413a-aac1-b59ab040edee"),
	SMS("0bc15338-aad9-41c7-b770-23bb699f115c"),
	twitter("189d143c-dfc9-4113-af12-d35f74834b53"),
	whatsapp("2e16ed7e-0b37-42cd-ba5d-dafd25abc3e1");

	private final java.lang.String i18nCaptionKey;
	
	private ShareToType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
