// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public enum ShareToType
{
	email("18603ceb-fc3a-4a90-ad1a-4cdd53b2f84b"),
	facebook("6f3708ea-7f40-4ba4-be8b-4000ab393254"),
	instagram("74752143-87bc-40dd-9725-0492b4ddf9e7"),
	linkedin("ec369c65-1980-4460-94c8-75abd1909b05"),
	pinterest("2ff41c19-d7bc-473b-adb1-1a87ace9fc09"),
	SMS("72074822-e443-4323-8113-471e4da5a7f9"),
	twitter("6b54495e-ac71-4353-a2ef-348581183a0e"),
	whatsapp("f8ac1deb-3f48-440c-9497-93f3aa912f56");

	private final java.lang.String i18nCaptionKey;
	
	private ShareToType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
