// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("edbda31e-d0ee-47b5-b6ce-c637fd65d4a7"),
	denied("03e36bca-a4b7-490c-a106-500de5d88f1d"),
	limited("484710a1-a2ca-4643-aee2-a036c291e75a"),
	granted("ac691186-3cd7-4d16-b18b-3eaa275047e5"),
	blocked("e472abc5-8a3c-44e3-a785-b597c0b2eb6b");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
