// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("b57ec52e-044c-4ace-9ead-e4dcfdf54ec8"),
	denied("e053d714-ff35-49b1-bc75-ed384d49ea05"),
	limited("00755653-f7d7-4144-ad87-c46f15e0902b"),
	granted("189bfa70-7e99-4050-8878-faa89d20caf4"),
	blocked("8fe4d672-05b3-42a2-9771-6a631798ef83");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
