// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("cd6d082e-19a2-46b2-bbbf-8b01429f31dc"),
	low("33fc5197-8cce-4ee0-b157-08fa70c7793d"),
	medium("2e1afd7e-8014-4842-affa-b8c8e7409022"),
	high("6da054c3-ae29-4ce5-829c-4286ed620792"),
	custom("3576cdd7-b6f7-4f21-9c3c-d12389d370a2");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
