// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("664ab7ad-a009-48be-8c90-8f44294e349a"),
	low("c803ba3a-a20b-46a5-b0cb-def8245df51c"),
	medium("23fda894-c590-4b5a-93ac-53f346d8ae20"),
	high("4ca74e4b-0407-44b5-a8f2-e89619150583"),
	custom("c83ee0f7-bdb6-402a-869e-f4afbbc3d48b");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
