// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum StatusBarHideShowAnimation
{
	none("3890ee80-9fba-4bf9-9ff6-c1efb7c3b77f"),
	fade("c0bbae74-f8d7-491d-b0af-1c59243df771"),
	slide("7c0c8657-0863-4c3f-8ae1-2f37ea00f0d9");

	private final java.lang.String i18nCaptionKey;
	
	private StatusBarHideShowAnimation(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
